### ISSUE TITLE
ACTIVIDAD 7 YAEL TRINIDAD 

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-7-YaelTrinidad#1]
[LINEA DEL TIEMPO ACT 7 YAEL TRINIDAD.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-YaelTrinidad/files/9768710/LINEA.DEL.TIEMPO.ACT.7.YAEL.TRINIDAD.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, de un total del 20% has obtenido un 17.2%, debido a que algunas fechas no concuerdan, la presentación del uso de colores es simple, te faltaron fechas más específicas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
