### ISSUE TITLE
agregar texto 

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-7-YaelTrinidad#2]
se agrega mas texto?

**Comment by Yabin-2021** [comment]
Yo considero que sí!!

**Comment by Yabin-2021** [comment]
Sale otro compañero diciendo que no

**Comment by Yabin-2021** [comment]
Y las incidencias son para discutir una problemática

**Comment by Yabin-2021** [comment]
Ya acordamos que sí!!!
